### ISSUE TITLE
请问这份代码需要怎么样的环境？

### ISSUE THREAD

**Issue by Xuanwo** [upsuper/white#1]

**Comment by upsuper** [comment]
见[README.zh_CN.md](https://github.com/upsuper/white/blob/master/README.zh_CN.md)

**Comment by Xuanwo** [comment]
版本啊- -

**Comment by upsuper** [comment]
这我就不记得了……当初写的时候没研究依赖……
不过即使有问题，修起来应该也不是很困难……

**Comment by Xuanwo** [comment]
咳- -，我照着时间安装了对应的版本，已经能跑起来了，2333
